export type DefaultPermissionSeed = {
  key: string;
  label: string;
  description: string;
  is_founder_only: boolean;
};

export const DEFAULT_PERMISSION_SEED: DefaultPermissionSeed[] = [
  { key: 'members.view', label: 'View members', description: 'View users and member profiles.', is_founder_only: false },
  { key: 'members.create', label: 'Create members', description: 'Create members directly.', is_founder_only: false },
  { key: 'members.invite', label: 'Invite members', description: 'Invite users to organisation.', is_founder_only: false },
  { key: 'members.edit_roles', label: 'Edit member roles', description: 'Assign and update member role assignments.', is_founder_only: false },
  { key: 'members.edit_status', label: 'Edit member status', description: 'Activate/deactivate members.', is_founder_only: false },
  { key: 'members.remove', label: 'Remove members', description: 'Remove users from organisation.', is_founder_only: false },
  { key: 'approvals.members.review', label: 'Review member approvals', description: 'Approve or reject pending members.', is_founder_only: false },
  { key: 'roles.view', label: 'View role permissions', description: 'View org role permission matrix.', is_founder_only: false },
  { key: 'roles.manage', label: 'Manage roles', description: 'Create/update/archive roles and grants.', is_founder_only: false },
  { key: 'departments.view', label: 'View departments', description: 'View department structures.', is_founder_only: false },
  { key: 'departments.create', label: 'Create departments', description: 'Create departments.', is_founder_only: false },
  { key: 'departments.edit', label: 'Edit departments', description: 'Update/archive departments.', is_founder_only: false },
  { key: 'departments.manage', label: 'Manage departments', description: 'Manage departments and structures.', is_founder_only: false },
  { key: 'teams.view', label: 'View teams', description: 'View teams and assignments.', is_founder_only: false },
  { key: 'teams.create', label: 'Create teams', description: 'Create teams.', is_founder_only: false },
  { key: 'teams.edit', label: 'Edit teams', description: 'Update/archive teams.', is_founder_only: false },
  { key: 'teams.manage', label: 'Manage teams', description: 'Manage teams and assignments.', is_founder_only: false },
  { key: 'broadcasts.view', label: 'View broadcasts', description: 'View broadcast feed and detail.', is_founder_only: false },
  { key: 'broadcasts.compose', label: 'Compose broadcasts', description: 'Create draft broadcasts.', is_founder_only: false },
  { key: 'broadcasts.publish', label: 'Publish broadcasts', description: 'Send scheduled/immediate broadcasts.', is_founder_only: false },
  { key: 'broadcasts.publish_without_approval', label: 'Publish without approval', description: 'Skip approval requirement for sends.', is_founder_only: false },
  { key: 'broadcasts.approve', label: 'Approve broadcasts', description: 'Approve pending broadcasts.', is_founder_only: false },
  { key: 'rota.view', label: 'View rota', description: 'View rota schedules.', is_founder_only: false },
  { key: 'rota.create', label: 'Create rota', description: 'Create rota definitions.', is_founder_only: false },
  { key: 'rota.edit', label: 'Edit rota', description: 'Edit rota definitions and shifts.', is_founder_only: false },
  { key: 'rota.manage', label: 'Manage rota', description: 'Create/edit rota definitions and shifts.', is_founder_only: false },
  { key: 'rota.final_approve', label: 'Final approve rota changes', description: 'Approve rota swaps/changes.', is_founder_only: false },
  { key: 'discounts.view', label: 'View discounts', description: 'View discount rules and cards.', is_founder_only: false },
  { key: 'discounts.verify_qr', label: 'Verify staff discount QR', description: 'Use discount verification scanner.', is_founder_only: false },
  { key: 'org.settings.view', label: 'View org settings', description: 'View organisation settings.', is_founder_only: false },
  { key: 'org.settings.manage', label: 'Manage org settings', description: 'Change organisation settings.', is_founder_only: false },
  { key: 'integrations.view', label: 'View integrations', description: 'View integrations status.', is_founder_only: false },
  { key: 'integrations.manage', label: 'Manage integrations', description: 'Manage integrations and credentials.', is_founder_only: false },
  { key: 'recruitment.view', label: 'View recruitment requests', description: 'View recruitment requests.', is_founder_only: false },
  { key: 'recruitment.create_request', label: 'Create recruitment requests', description: 'Raise recruitment requests.', is_founder_only: false },
  { key: 'recruitment.approve_request', label: 'Approve recruitment requests', description: 'Approve/reject recruitment requests.', is_founder_only: false },
  { key: 'recruitment.manage', label: 'Manage recruitment', description: 'Manage recruitment requests.', is_founder_only: false },
  { key: 'jobs.view', label: 'View jobs', description: 'View job listings.', is_founder_only: false },
  { key: 'jobs.create', label: 'Create jobs', description: 'Create job listings from requests.', is_founder_only: false },
  { key: 'jobs.edit', label: 'Edit jobs', description: 'Edit job details and copy.', is_founder_only: false },
  { key: 'jobs.publish', label: 'Publish jobs', description: 'Publish jobs to public URL.', is_founder_only: false },
  { key: 'jobs.archive', label: 'Archive jobs', description: 'Archive job listings.', is_founder_only: false },
  { key: 'jobs.manage', label: 'Manage jobs', description: 'Manage job listings.', is_founder_only: false },
  { key: 'applications.view', label: 'View applications', description: 'View candidate applications.', is_founder_only: false },
  { key: 'applications.move_stage', label: 'Move application stage', description: 'Move candidates through hiring stages.', is_founder_only: false },
  { key: 'applications.notify_candidate', label: 'Notify candidates', description: 'Send candidate status messages/emails.', is_founder_only: false },
  { key: 'applications.add_internal_notes', label: 'Add internal notes', description: 'Add internal candidate notes.', is_founder_only: false },
  { key: 'applications.manage', label: 'Manage applications', description: 'Manage job applications.', is_founder_only: false },
  { key: 'offers.view', label: 'View offers', description: 'View generated offer letters.', is_founder_only: false },
  { key: 'offers.generate', label: 'Generate offers', description: 'Generate offer letters from templates.', is_founder_only: false },
  { key: 'offers.send_esign', label: 'Send e-sign offers', description: 'Send offer letters for e-signature.', is_founder_only: false },
  { key: 'offers.view_signed_pdf', label: 'View signed offer PDFs', description: 'Download signed offer PDFs.', is_founder_only: false },
  { key: 'offers.manage', label: 'Manage offers', description: 'Manage offer templates and offer letters.', is_founder_only: false },
  { key: 'interviews.view', label: 'View interviews', description: 'View interview schedule.', is_founder_only: false },
  { key: 'interviews.create_slot', label: 'Create interview slots', description: 'Create interview slots.', is_founder_only: false },
  { key: 'interviews.book_slot', label: 'Book interview slots', description: 'Book slots when scheduling candidates.', is_founder_only: false },
  { key: 'interviews.complete_slot', label: 'Complete interview slots', description: 'Mark interview slots as completed.', is_founder_only: false },
  { key: 'interviews.manage', label: 'Manage interviews', description: 'Manage interview schedule.', is_founder_only: false },
  { key: 'leave.submit', label: 'Submit leave', description: 'Submit annual leave, TOIL, and sickness for self.', is_founder_only: false },
  {
    key: 'leave.view_own',
    label: 'View own leave',
    description: 'View own leave balances, requests, and sickness absence score.',
    is_founder_only: false,
  },
  { key: 'leave.view_direct_reports', label: 'View team leave', description: 'View leave and sickness for direct reports.', is_founder_only: false },
  { key: 'leave.approve_direct_reports', label: 'Approve direct reports leave', description: 'Approve or reject leave for users who report to you.', is_founder_only: false },
  { key: 'leave.manage_org', label: 'Manage organisation leave', description: 'Set allowances, org leave settings, approve any request.', is_founder_only: false },
  { key: 'hr.view_own', label: 'View own HR record', description: 'View your own HR record including job title, contract type, and employment dates.', is_founder_only: false },
  { key: 'hr.view_direct_reports', label: 'View direct reports HR records', description: 'View HR records and employment details for employees who report directly to you.', is_founder_only: false },
  { key: 'hr.view_records', label: 'View HR records', description: 'View employee HR files including contract details and employment dates.', is_founder_only: false },
  { key: 'hr.manage_records', label: 'Manage HR records', description: 'Create and edit employee HR records, contract type, salary band, employment dates.', is_founder_only: false },
  { key: 'hr.employee_photo.view_all', label: 'View employee photos (all)', description: 'View employee profile photos across the organisation.', is_founder_only: false },
  { key: 'hr.employee_photo.manage_all', label: 'Manage employee photos (all)', description: 'Upload, replace, and delete employee photos across the organisation.', is_founder_only: false },
  { key: 'hr.employee_photo.view_own', label: 'View own employee photo', description: 'View and download your own employee photo files.', is_founder_only: false },
  { key: 'hr.employee_photo.upload_own', label: 'Upload own employee photo', description: 'Upload or replace your own employee photo files.', is_founder_only: false },
  { key: 'hr.employee_photo.delete_own', label: 'Delete own employee photo', description: 'Delete your own employee photo files.', is_founder_only: false },
  { key: 'hr.id_document.view_all', label: 'View ID documents (all)', description: 'View employee identity documents across the organisation.', is_founder_only: false },
  { key: 'hr.id_document.manage_all', label: 'Manage ID documents (all)', description: 'Upload, replace, and delete employee identity documents across the organisation.', is_founder_only: false },
  { key: 'hr.id_document.view_own', label: 'View own ID documents', description: 'View and download your own identity documents.', is_founder_only: false },
  { key: 'hr.id_document.upload_own', label: 'Upload own ID documents', description: 'Upload your own identity documents.', is_founder_only: false },
  { key: 'hr.id_document.delete_own', label: 'Delete own ID documents', description: 'Delete your own identity documents.', is_founder_only: false },
  { key: 'hr.employment_history.view_all', label: 'View employment history (all)', description: 'View employment history timelines for all employees.', is_founder_only: false },
  { key: 'hr.employment_history.manage_all', label: 'Manage employment history (all)', description: 'Create, edit, and delete employment history timelines for all employees.', is_founder_only: false },
  { key: 'hr.employment_history.view_own', label: 'View own employment history', description: 'View your own employment history timeline.', is_founder_only: false },
  { key: 'hr.employment_history.manage_own', label: 'Manage own employment history', description: 'Submit and maintain your own employment history timeline.', is_founder_only: false },
  { key: 'hr.disciplinary.view_all', label: 'View disciplinary records (all)', description: 'View disciplinary records across the organisation.', is_founder_only: false },
  { key: 'hr.disciplinary.manage_all', label: 'Manage disciplinary records (all)', description: 'Create, edit, and archive disciplinary records across the organisation.', is_founder_only: false },
  { key: 'hr.disciplinary.view_own', label: 'View own disciplinary records', description: 'View your own disciplinary records and outcomes.', is_founder_only: false },
  { key: 'hr.grievance.view_all', label: 'View grievance records (all)', description: 'View grievance records across the organisation.', is_founder_only: false },
  { key: 'hr.grievance.manage_all', label: 'Manage grievance records (all)', description: 'Create, edit, and archive grievance records across the organisation.', is_founder_only: false },
  { key: 'hr.grievance.view_own', label: 'View own grievance records', description: 'View your own grievance records and outcomes.', is_founder_only: false },
  { key: 'hr.medical_notes.view_all', label: 'View medical notes (all)', description: 'View medical and occupational health case summaries for all employees.', is_founder_only: false },
  { key: 'hr.medical_notes.manage_all', label: 'Manage medical notes (all)', description: 'Create, update, and archive medical and occupational health cases for all employees.', is_founder_only: false },
  { key: 'hr.medical_notes.view_own_summary', label: 'View own medical summary', description: 'View your own medical and occupational health outcomes and summary fields.', is_founder_only: false },
  { key: 'hr.medical_notes.reveal_sensitive', label: 'Reveal sensitive medical notes', description: 'Reveal encrypted sensitive medical notes with reason and audit trail.', is_founder_only: false },
  { key: 'hr.medical_notes.export', label: 'Export medical notes', description: 'Export medical and occupational health records with audit logging.', is_founder_only: false },
  { key: 'hr.medical_notes.manage_own', label: 'Manage own medical submissions', description: 'Submit or update your own medical and occupational health referrals.', is_founder_only: false },
  { key: 'hr.custom_fields.view', label: 'View custom HR fields', description: 'View custom HR field definitions and values.', is_founder_only: false },
  { key: 'hr.custom_fields.manage_definitions', label: 'Manage custom HR field definitions', description: 'Create, update, and archive custom HR field definitions for the organisation.', is_founder_only: false },
  { key: 'hr.custom_fields.manage_values_all', label: 'Manage custom HR field values (all)', description: 'Manage custom HR field values for all employees.', is_founder_only: false },
  { key: 'hr.custom_fields.manage_values_own', label: 'Manage own custom HR field values', description: 'Manage your own custom HR field values.', is_founder_only: false },
  { key: 'privacy.retention_policy.view', label: 'View retention policies', description: 'View organisation data retention policies.', is_founder_only: false },
  { key: 'privacy.retention_policy.manage', label: 'Manage retention policies', description: 'Create and update organisation data retention policies.', is_founder_only: false },
  { key: 'privacy.erasure_request.create', label: 'Create erasure requests', description: 'Create GDPR right-to-erasure requests.', is_founder_only: false },
  { key: 'privacy.erasure_request.review', label: 'Review erasure requests', description: 'Review and approve or reject erasure requests.', is_founder_only: false },
  { key: 'privacy.erasure_request.execute', label: 'Execute erasure requests', description: 'Execute approved erasure workflows.', is_founder_only: false },
  { key: 'privacy.erasure_request.audit_view', label: 'View erasure audit log', description: 'View audit logs for erasure requests.', is_founder_only: false },
  { key: 'hr.records_export.view_all', label: 'Export employee records (all)', description: 'Generate employee record exports for any employee.', is_founder_only: false },
  { key: 'hr.records_export.view_own', label: 'Export own employee record', description: 'Generate your own employee record export.', is_founder_only: false },
  { key: 'hr.records_export.view_direct_reports', label: 'Export direct report records', description: 'Generate employee record exports for direct reports.', is_founder_only: false },
  { key: 'hr.records_export.include_sensitive', label: 'Include sensitive fields in export', description: 'Allow inclusion of sensitive fields in employee record export with reason.', is_founder_only: false },
  { key: 'hr.records_export.generate_pdf', label: 'Generate PDF employee exports', description: 'Generate employee record exports in PDF format.', is_founder_only: false },
  { key: 'hr.records_export.generate_csv', label: 'Generate CSV employee exports', description: 'Generate employee record exports in CSV format.', is_founder_only: false },
  { key: 'payroll.bank_details.view_all', label: 'View bank details (all)', description: 'View masked payroll bank details for all employees.', is_founder_only: false },
  { key: 'payroll.bank_details.manage_all', label: 'Manage bank details (all)', description: 'Create, approve, reject, and activate payroll bank details for all employees.', is_founder_only: false },
  { key: 'payroll.bank_details.view_own', label: 'View own bank details', description: 'View your own masked payroll bank details.', is_founder_only: false },
  { key: 'payroll.bank_details.manage_own', label: 'Manage own bank details', description: 'Submit updates to your own payroll bank details.', is_founder_only: false },
  { key: 'payroll.bank_details.export', label: 'Export payroll bank details', description: 'Export decrypted payroll bank details for payroll runs.', is_founder_only: false },
  { key: 'payroll.uk_tax.view_all', label: 'View UK tax details (all)', description: 'View masked NI/tax details for all employees.', is_founder_only: false },
  { key: 'payroll.uk_tax.manage_all', label: 'Manage UK tax details (all)', description: 'Create, approve, reject, and activate UK tax details for all employees.', is_founder_only: false },
  { key: 'payroll.uk_tax.view_own', label: 'View own UK tax details', description: 'View your own masked NI/tax details.', is_founder_only: false },
  { key: 'payroll.uk_tax.manage_own', label: 'Manage own UK tax details', description: 'Submit updates to your own NI/tax details.', is_founder_only: false },
  { key: 'payroll.uk_tax.export', label: 'Export UK tax details', description: 'Export decrypted NI/tax details for payroll.', is_founder_only: false },
  { key: 'payroll.tax_docs.view_all', label: 'View tax documents (all)', description: 'View employee P45/P60 payroll documents for the organisation.', is_founder_only: false },
  { key: 'payroll.tax_docs.manage_all', label: 'Manage tax documents (all)', description: 'Upload, replace, and delete employee P45/P60 payroll documents for the organisation.', is_founder_only: false },
  { key: 'payroll.tax_docs.view_own', label: 'View own tax documents', description: 'View and download your own P45/P60 documents.', is_founder_only: false },
  { key: 'payroll.tax_docs.upload_own', label: 'Upload own tax documents', description: 'Upload your own P45/P60 documents when enabled by policy.', is_founder_only: false },
  { key: 'payroll.tax_docs.export', label: 'Export tax document index', description: 'Export payroll tax document metadata for finance operations.', is_founder_only: false },
  { key: 'onboarding.manage_templates', label: 'Manage onboarding templates', description: 'Create and edit reusable onboarding checklist templates.', is_founder_only: false },
  { key: 'onboarding.manage_runs', label: 'Manage onboarding runs', description: 'Start, view, and manage active employee onboarding runs.', is_founder_only: false },
  { key: 'onboarding.complete_own_tasks', label: 'Complete own onboarding tasks', description: 'Employee can tick off tasks assigned to them in their onboarding checklist.', is_founder_only: false },
  { key: 'performance.manage_cycles', label: 'Manage review cycles', description: 'Create and manage performance review cycles, enroll employees.', is_founder_only: false },
  { key: 'performance.view_reports', label: 'View all reviews', description: 'View all performance reviews and ratings across the org.', is_founder_only: false },
  { key: 'performance.review_direct_reports', label: 'Review direct reports', description: 'Submit manager assessments for employees who report to you.', is_founder_only: false },
  { key: 'performance.view_own', label: 'View own reviews', description: 'Employee can view and complete their own performance review self-assessment.', is_founder_only: false },
  { key: 'one_on_one.view_own', label: 'View own 1:1 meetings', description: 'View 1:1 check-ins you participate in as manager or direct report.', is_founder_only: false },
  { key: 'one_on_one.view_all_checkins', label: 'View all 1:1 check-ins', description: 'View all scheduled and in-progress 1:1 check-ins across the organisation calendar.', is_founder_only: false },
  { key: 'one_on_one.manage_direct_reports', label: 'Manage 1:1s with direct reports', description: 'Schedule and complete 1:1 meetings with people who report to you.', is_founder_only: false },
  { key: 'one_on_one.manage_templates', label: 'Manage 1:1 templates and org settings', description: 'Edit org 1:1 cadence defaults and meeting templates.', is_founder_only: false },
  { key: 'org_chart.view', label: 'View org chart', description: 'View the live organisation chart with hierarchy and working presence.', is_founder_only: false },
  { key: 'reports.view', label: 'View reports', description: 'Access report builder, run reports, and view saved reports.', is_founder_only: false },
  { key: 'reports.manage', label: 'Manage reports', description: 'Manage shared reports, schedules, and cross-domain reporting.', is_founder_only: false },
  { key: 'founder.platform.manage', label: 'Founder platform access', description: 'Platform-global founder controls.', is_founder_only: true },
  { key: 'founder.billing.manage', label: 'Founder billing access', description: 'Billing and subscription controls.', is_founder_only: true },
  { key: 'founder.feature_flags.manage', label: 'Founder feature flags', description: 'Platform feature flag controls.', is_founder_only: true },
];

