export type DefaultPermissionSeed = {
  key: string;
  label: string;
  description: string;
  is_founder_only: boolean;
};

export const DEFAULT_PERMISSION_SEED: DefaultPermissionSeed[] = [
  { key: 'members.view', label: 'View members', description: 'View users and member profiles.', is_founder_only: false },
  { key: 'members.create', label: 'Create members', description: 'Create members directly.', is_founder_only: false },
  { key: 'members.invite', label: 'Invite members', description: 'Invite users to organisation.', is_founder_only: false },
  { key: 'members.edit_roles', label: 'Edit member roles', description: 'Assign and update member role assignments.', is_founder_only: false },
  { key: 'members.edit_status', label: 'Edit member status', description: 'Activate/deactivate members.', is_founder_only: false },
  { key: 'members.remove', label: 'Remove members', description: 'Remove users from organisation.', is_founder_only: false },
  { key: 'approvals.members.review', label: 'Review member approvals', description: 'Approve or reject pending members.', is_founder_only: false },
  { key: 'roles.view', label: 'View role permissions', description: 'View org role permission matrix.', is_founder_only: false },
  { key: 'roles.manage', label: 'Manage roles', description: 'Create/update/archive roles and grants.', is_founder_only: false },
  { key: 'departments.view', label: 'View departments', description: 'View department structures.', is_founder_only: false },
  { key: 'departments.create', label: 'Create departments', description: 'Create departments.', is_founder_only: false },
  { key: 'departments.edit', label: 'Edit departments', description: 'Update/archive departments.', is_founder_only: false },
  { key: 'departments.manage', label: 'Manage departments', description: 'Manage departments and structures.', is_founder_only: false },
  { key: 'teams.view', label: 'View teams', description: 'View teams and assignments.', is_founder_only: false },
  { key: 'teams.create', label: 'Create teams', description: 'Create teams.', is_founder_only: false },
  { key: 'teams.edit', label: 'Edit teams', description: 'Update/archive teams.', is_founder_only: false },
  { key: 'teams.manage', label: 'Manage teams', description: 'Manage teams and assignments.', is_founder_only: false },
  { key: 'broadcasts.view', label: 'View broadcasts', description: 'View broadcast feed and detail.', is_founder_only: false },
  { key: 'broadcasts.compose', label: 'Compose broadcasts', description: 'Create draft broadcasts.', is_founder_only: false },
  { key: 'broadcasts.publish', label: 'Publish broadcasts', description: 'Send scheduled/immediate broadcasts.', is_founder_only: false },
  { key: 'broadcasts.publish_without_approval', label: 'Publish without approval', description: 'Skip approval requirement for sends.', is_founder_only: false },
  { key: 'broadcasts.approve', label: 'Approve broadcasts', description: 'Approve pending broadcasts.', is_founder_only: false },
  { key: 'rota.view', label: 'View rota', description: 'View rota schedules.', is_founder_only: false },
  { key: 'rota.create', label: 'Create rota', description: 'Create rota definitions.', is_founder_only: false },
  { key: 'rota.edit', label: 'Edit rota', description: 'Edit rota definitions and shifts.', is_founder_only: false },
  { key: 'rota.manage', label: 'Manage rota', description: 'Create/edit rota definitions and shifts.', is_founder_only: false },
  { key: 'rota.final_approve', label: 'Final approve rota changes', description: 'Approve rota swaps/changes.', is_founder_only: false },
  { key: 'discounts.view', label: 'View discounts', description: 'View discount rules and cards.', is_founder_only: false },
  { key: 'discounts.verify_qr', label: 'Verify staff discount QR', description: 'Use discount verification scanner.', is_founder_only: false },
  { key: 'org.settings.view', label: 'View org settings', description: 'View organisation settings.', is_founder_only: false },
  { key: 'org.settings.manage', label: 'Manage org settings', description: 'Change organisation settings.', is_founder_only: false },
  { key: 'integrations.view', label: 'View integrations', description: 'View integrations status.', is_founder_only: false },
  { key: 'integrations.manage', label: 'Manage integrations', description: 'Manage integrations and credentials.', is_founder_only: false },
  { key: 'recruitment.view', label: 'View recruitment requests', description: 'View recruitment requests.', is_founder_only: false },
  { key: 'recruitment.create_request', label: 'Create recruitment requests', description: 'Raise recruitment requests.', is_founder_only: false },
  { key: 'recruitment.approve_request', label: 'Approve recruitment requests', description: 'Approve/reject recruitment requests.', is_founder_only: false },
  { key: 'recruitment.manage', label: 'Manage recruitment', description: 'Manage recruitment requests.', is_founder_only: false },
  { key: 'jobs.view', label: 'View jobs', description: 'View job listings.', is_founder_only: false },
  { key: 'jobs.create', label: 'Create jobs', description: 'Create job listings from requests.', is_founder_only: false },
  { key: 'jobs.edit', label: 'Edit jobs', description: 'Edit job details and copy.', is_founder_only: false },
  { key: 'jobs.publish', label: 'Publish jobs', description: 'Publish jobs to public URL.', is_founder_only: false },
  { key: 'jobs.archive', label: 'Archive jobs', description: 'Archive job listings.', is_founder_only: false },
  { key: 'jobs.manage', label: 'Manage jobs', description: 'Manage job listings.', is_founder_only: false },
  { key: 'applications.view', label: 'View applications', description: 'View candidate applications.', is_founder_only: false },
  { key: 'applications.move_stage', label: 'Move application stage', description: 'Move candidates through hiring stages.', is_founder_only: false },
  { key: 'applications.notify_candidate', label: 'Notify candidates', description: 'Send candidate status messages/emails.', is_founder_only: false },
  { key: 'applications.add_internal_notes', label: 'Add internal notes', description: 'Add internal candidate notes.', is_founder_only: false },
  { key: 'applications.manage', label: 'Manage applications', description: 'Manage job applications.', is_founder_only: false },
  { key: 'offers.view', label: 'View offers', description: 'View generated offer letters.', is_founder_only: false },
  { key: 'offers.generate', label: 'Generate offers', description: 'Generate offer letters from templates.', is_founder_only: false },
  { key: 'offers.send_esign', label: 'Send e-sign offers', description: 'Send offer letters for e-signature.', is_founder_only: false },
  { key: 'offers.view_signed_pdf', label: 'View signed offer PDFs', description: 'Download signed offer PDFs.', is_founder_only: false },
  { key: 'offers.manage', label: 'Manage offers', description: 'Manage offer templates and offer letters.', is_founder_only: false },
  { key: 'interviews.view', label: 'View interviews', description: 'View interview schedule.', is_founder_only: false },
  { key: 'interviews.create_slot', label: 'Create interview slots', description: 'Create interview slots.', is_founder_only: false },
  { key: 'interviews.book_slot', label: 'Book interview slots', description: 'Book slots when scheduling candidates.', is_founder_only: false },
  { key: 'interviews.complete_slot', label: 'Complete interview slots', description: 'Mark interview slots as completed.', is_founder_only: false },
  { key: 'interviews.manage', label: 'Manage interviews', description: 'Manage interview schedule.', is_founder_only: false },
  { key: 'leave.submit', label: 'Submit leave', description: 'Submit annual leave, TOIL, and sickness for self.', is_founder_only: false },
  {
    key: 'leave.view_own',
    label: 'View own leave',
    description: 'View own leave balances, requests, and sickness absence score.',
    is_founder_only: false,
  },
  { key: 'leave.view_direct_reports', label: 'View team leave', description: 'View leave and sickness for direct reports.', is_founder_only: false },
  { key: 'leave.approve_direct_reports', label: 'Approve direct reports leave', description: 'Approve or reject leave for users who report to you.', is_founder_only: false },
  { key: 'leave.manage_org', label: 'Manage organisation leave', description: 'Set allowances, org leave settings, approve any request.', is_founder_only: false },
  { key: 'hr.view_records', label: 'View HR records', description: 'View employee HR files including contract details and employment dates.', is_founder_only: false },
  { key: 'hr.manage_records', label: 'Manage HR records', description: 'Create and edit employee HR records, contract type, salary band, employment dates.', is_founder_only: false },
  { key: 'onboarding.manage_templates', label: 'Manage onboarding templates', description: 'Create and edit reusable onboarding checklist templates.', is_founder_only: false },
  { key: 'onboarding.manage_runs', label: 'Manage onboarding runs', description: 'Start, view, and manage active employee onboarding runs.', is_founder_only: false },
  { key: 'onboarding.complete_own_tasks', label: 'Complete own onboarding tasks', description: 'Employee can tick off tasks assigned to them in their onboarding checklist.', is_founder_only: false },
  { key: 'founder.platform.manage', label: 'Founder platform access', description: 'Platform-global founder controls.', is_founder_only: true },
  { key: 'founder.billing.manage', label: 'Founder billing access', description: 'Billing and subscription controls.', is_founder_only: true },
  { key: 'founder.feature_flags.manage', label: 'Founder feature flags', description: 'Platform feature flag controls.', is_founder_only: true },
];

