-- Founder portal expansion: versioned RBAC catalog, presets, audit, and governance controls.

create table if not exists public.platform_permission_catalog_versions (
  version_no bigint generated by default as identity primary key,
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_by uuid references auth.users(id) on delete set null,
  published_by uuid references auth.users(id) on delete set null,
  publish_note text not null default '',
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.platform_permission_catalog_entries (
  version_no bigint not null references public.platform_permission_catalog_versions(version_no) on delete cascade,
  key text not null,
  label text not null,
  description text not null default '',
  category text not null default 'other',
  is_founder_only boolean not null default false,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint platform_permission_catalog_entries_pkey primary key (version_no, key)
);

create table if not exists public.platform_role_presets (
  id uuid primary key default gen_random_uuid(),
  source_version_no bigint not null references public.platform_permission_catalog_versions(version_no) on delete cascade,
  key text not null,
  name text not null,
  description text not null default '',
  target_use_case text not null default '',
  recommended_permission_keys text[] not null default '{}',
  is_archived boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_version_no, key)
);

create table if not exists public.platform_audit_events (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid references auth.users(id) on delete set null,
  org_id uuid references public.organisations(id) on delete set null,
  event_type text not null,
  entity_type text not null,
  entity_id text not null,
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists platform_permission_catalog_entries_version_idx
  on public.platform_permission_catalog_entries(version_no, category, key);
create index if not exists platform_role_presets_version_idx
  on public.platform_role_presets(source_version_no, is_archived, name);
create index if not exists platform_audit_events_created_idx
  on public.platform_audit_events(created_at desc);
create index if not exists platform_audit_events_org_event_idx
  on public.platform_audit_events(org_id, event_type, created_at desc);

alter table public.org_roles
  add column if not exists source_preset_id uuid references public.platform_role_presets(id) on delete set null;
alter table public.org_roles
  add column if not exists source_catalog_version_no bigint;

alter table public.organisations
  add column if not exists plan_tier text not null default 'starter';
alter table public.organisations
  add column if not exists subscription_status text not null default 'active'
  check (subscription_status in ('active', 'limited', 'suspended'));
alter table public.organisations
  add column if not exists is_locked boolean not null default false;
alter table public.organisations
  add column if not exists maintenance_mode boolean not null default false;
alter table public.organisations
  add column if not exists force_logout_after timestamptz;

create or replace function public.platform_is_founder(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.platform_admins pa
    where pa.user_id = p_user_id
  );
$$;

create or replace function public.platform_latest_published_catalog_version()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select v.version_no
  from public.platform_permission_catalog_versions v
  where v.status = 'published'
  order by v.version_no desc
  limit 1
$$;

create or replace function public.platform_latest_draft_catalog_version()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select v.version_no
  from public.platform_permission_catalog_versions v
  where v.status = 'draft'
  order by v.version_no desc
  limit 1
$$;

create or replace function public.platform_ensure_latest_draft_catalog()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_draft bigint;
  v_source bigint;
begin
  select public.platform_latest_draft_catalog_version() into v_draft;
  if v_draft is not null then
    return v_draft;
  end if;

  select public.platform_latest_published_catalog_version() into v_source;

  insert into public.platform_permission_catalog_versions (status, created_by)
  values ('draft', auth.uid())
  returning version_no into v_draft;

  if v_source is not null then
    insert into public.platform_permission_catalog_entries (
      version_no, key, label, description, category, is_founder_only, is_archived
    )
    select
      v_draft, e.key, e.label, e.description, e.category, e.is_founder_only, e.is_archived
    from public.platform_permission_catalog_entries e
    where e.version_no = v_source
    on conflict (version_no, key) do nothing;
  else
    insert into public.platform_permission_catalog_entries (
      version_no, key, label, description, category, is_founder_only, is_archived
    )
    select
      v_draft,
      pc.key,
      pc.label,
      pc.description,
      split_part(pc.key, '.', 1),
      pc.is_founder_only,
      false
    from public.permission_catalog pc
    on conflict (version_no, key) do nothing;
  end if;

  return v_draft;
end;
$$;

create or replace function public.platform_founder_catalog_draft()
returns table (
  version_no bigint,
  key text,
  label text,
  description text,
  category text,
  is_founder_only boolean,
  is_archived boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_draft bigint;
begin
  if not public.platform_is_founder(auth.uid()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  select public.platform_ensure_latest_draft_catalog() into v_draft;
  return query
  select
    e.version_no, e.key, e.label, e.description, e.category, e.is_founder_only, e.is_archived
  from public.platform_permission_catalog_entries e
  where e.version_no = v_draft
  order by e.category, e.key;
end;
$$;

create or replace function public.platform_upsert_catalog_draft_entry(
  p_key text,
  p_label text,
  p_description text,
  p_category text,
  p_is_founder_only boolean,
  p_is_archived boolean
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_draft bigint;
  v_key text := lower(trim(coalesce(p_key, '')));
begin
  if not public.platform_is_founder(auth.uid()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  if v_key = '' then
    raise exception 'permission key required';
  end if;
  if trim(coalesce(p_label, '')) = '' then
    raise exception 'permission label required';
  end if;
  select public.platform_ensure_latest_draft_catalog() into v_draft;

  insert into public.platform_permission_catalog_entries (
    version_no, key, label, description, category, is_founder_only, is_archived, updated_at
  )
  values (
    v_draft,
    v_key,
    trim(p_label),
    coalesce(p_description, ''),
    case when trim(coalesce(p_category, '')) = '' then split_part(v_key, '.', 1) else lower(trim(p_category)) end,
    coalesce(p_is_founder_only, false),
    coalesce(p_is_archived, false),
    now()
  )
  on conflict (version_no, key) do update
  set
    label = excluded.label,
    description = excluded.description,
    category = excluded.category,
    is_founder_only = excluded.is_founder_only,
    is_archived = excluded.is_archived,
    updated_at = now();

  insert into public.platform_audit_events (
    actor_user_id, event_type, entity_type, entity_id, after_state, metadata
  )
  values (
    auth.uid(),
    'catalog.draft_entry_upserted',
    'permission_catalog_entry',
    v_key,
    jsonb_build_object(
      'version_no', v_draft,
      'key', v_key,
      'label', trim(p_label),
      'category', case when trim(coalesce(p_category, '')) = '' then split_part(v_key, '.', 1) else lower(trim(p_category)) end
    ),
    '{}'::jsonb
  );

  return v_draft;
end;
$$;

create or replace function public.platform_publish_catalog(
  p_publish_note text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_draft bigint;
begin
  if not public.platform_is_founder(auth.uid()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  select public.platform_ensure_latest_draft_catalog() into v_draft;

  update public.platform_permission_catalog_versions
  set status = 'published', published_by = auth.uid(), published_at = now(), publish_note = coalesce(p_publish_note, '')
  where version_no = v_draft;

  insert into public.permission_catalog (key, label, description, is_founder_only)
  select e.key, e.label, e.description, e.is_founder_only
  from public.platform_permission_catalog_entries e
  where e.version_no = v_draft
    and e.is_archived = false
  on conflict (key) do update
  set
    label = excluded.label,
    description = excluded.description,
    is_founder_only = excluded.is_founder_only;

  delete from public.permission_catalog pc
  where not exists (
    select 1
    from public.platform_permission_catalog_entries e
    where e.version_no = v_draft
      and e.key = pc.key
      and e.is_archived = false
  );

  insert into public.platform_audit_events (
    actor_user_id, event_type, entity_type, entity_id, after_state, metadata
  )
  values (
    auth.uid(),
    'catalog.published',
    'permission_catalog_version',
    v_draft::text,
    jsonb_build_object('version_no', v_draft, 'publish_note', coalesce(p_publish_note, '')),
    '{}'::jsonb
  );

  return v_draft;
end;
$$;

create or replace function public.platform_active_permission_catalog()
returns table (
  version_no bigint,
  key text,
  label text,
  description text,
  category text,
  is_founder_only boolean,
  is_archived boolean
)
language sql
stable
security definer
set search_path = public
as $$
  with v as (
    select public.platform_latest_published_catalog_version() as version_no
  )
  select
    e.version_no, e.key, e.label, e.description, e.category, e.is_founder_only, e.is_archived
  from v
  join public.platform_permission_catalog_entries e on e.version_no = v.version_no
  where e.is_archived = false
  order by e.category, e.key
$$;

create or replace function public.platform_list_role_presets(
  p_include_archived boolean default false
)
returns table (
  id uuid,
  source_version_no bigint,
  key text,
  name text,
  description text,
  target_use_case text,
  recommended_permission_keys text[],
  is_archived boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_version bigint;
begin
  v_version := public.platform_latest_published_catalog_version();
  if v_version is null then
    return;
  end if;

  return query
  select
    p.id,
    p.source_version_no,
    p.key,
    p.name,
    p.description,
    p.target_use_case,
    p.recommended_permission_keys,
    p.is_archived
  from public.platform_role_presets p
  where p.source_version_no = v_version
    and (p_include_archived or p.is_archived = false)
  order by p.name;
end;
$$;

create or replace function public.platform_founder_upsert_role_preset(
  p_key text,
  p_name text,
  p_description text,
  p_target_use_case text,
  p_recommended_permission_keys text[],
  p_is_archived boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_version bigint;
  v_key text := lower(trim(coalesce(p_key, '')));
  v_id uuid;
begin
  if not public.platform_is_founder(auth.uid()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  if v_key = '' then
    raise exception 'preset key required';
  end if;
  if trim(coalesce(p_name, '')) = '' then
    raise exception 'preset name required';
  end if;

  v_version := public.platform_latest_published_catalog_version();
  if v_version is null then
    v_version := public.platform_publish_catalog('Auto-publish baseline before creating role presets.');
  end if;

  insert into public.platform_role_presets (
    source_version_no, key, name, description, target_use_case, recommended_permission_keys, is_archived, created_by
  )
  values (
    v_version,
    v_key,
    trim(p_name),
    coalesce(p_description, ''),
    coalesce(p_target_use_case, ''),
    coalesce(p_recommended_permission_keys, '{}'),
    coalesce(p_is_archived, false),
    auth.uid()
  )
  on conflict (source_version_no, key) do update
  set
    name = excluded.name,
    description = excluded.description,
    target_use_case = excluded.target_use_case,
    recommended_permission_keys = excluded.recommended_permission_keys,
    is_archived = excluded.is_archived,
    updated_at = now()
  returning id into v_id;

  insert into public.platform_audit_events (
    actor_user_id, event_type, entity_type, entity_id, after_state, metadata
  )
  values (
    auth.uid(),
    'preset.upserted',
    'role_preset',
    v_id::text,
    jsonb_build_object('id', v_id, 'source_version_no', v_version, 'key', v_key, 'name', trim(p_name)),
    '{}'::jsonb
  );

  return v_id;
end;
$$;

create or replace function public.platform_list_audit_events(
  p_org_id uuid default null,
  p_event_type text default null,
  p_days integer default 30
)
returns table (
  id uuid,
  actor_user_id uuid,
  org_id uuid,
  event_type text,
  entity_type text,
  entity_id text,
  before_state jsonb,
  after_state jsonb,
  metadata jsonb,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.platform_is_founder(auth.uid()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return query
  select
    a.id, a.actor_user_id, a.org_id, a.event_type, a.entity_type, a.entity_id, a.before_state, a.after_state, a.metadata, a.created_at
  from public.platform_audit_events a
  where (p_org_id is null or a.org_id = p_org_id)
    and (p_event_type is null or a.event_type = p_event_type)
    and a.created_at >= now() - make_interval(days => greatest(1, coalesce(p_days, 30)))
  order by a.created_at desc
  limit 500;
end;
$$;

create or replace function public.platform_update_org_governance(
  p_org_id uuid,
  p_plan_tier text,
  p_subscription_status text,
  p_is_locked boolean,
  p_maintenance_mode boolean,
  p_force_logout boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before jsonb;
begin
  if not public.platform_is_founder(auth.uid()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'plan_tier', o.plan_tier,
    'subscription_status', o.subscription_status,
    'is_locked', o.is_locked,
    'maintenance_mode', o.maintenance_mode,
    'force_logout_after', o.force_logout_after
  )
  into v_before
  from public.organisations o
  where o.id = p_org_id;

  update public.organisations
  set
    plan_tier = coalesce(nullif(trim(coalesce(p_plan_tier, '')), ''), plan_tier),
    subscription_status = case
      when p_subscription_status in ('active', 'limited', 'suspended') then p_subscription_status
      else subscription_status
    end,
    is_locked = coalesce(p_is_locked, is_locked),
    maintenance_mode = coalesce(p_maintenance_mode, maintenance_mode),
    force_logout_after = case when coalesce(p_force_logout, false) then now() else force_logout_after end
  where id = p_org_id;

  insert into public.platform_audit_events (
    actor_user_id, org_id, event_type, entity_type, entity_id, before_state, after_state, metadata
  )
  select
    auth.uid(),
    o.id,
    'org.governance_updated',
    'organisation',
    o.id::text,
    coalesce(v_before, '{}'::jsonb),
    jsonb_build_object(
      'plan_tier', o.plan_tier,
      'subscription_status', o.subscription_status,
      'is_locked', o.is_locked,
      'maintenance_mode', o.maintenance_mode,
      'force_logout_after', o.force_logout_after
    ),
    jsonb_build_object('force_logout_triggered', coalesce(p_force_logout, false))
  from public.organisations o
  where o.id = p_org_id;
end;
$$;

create or replace function public.platform_create_support_session(
  p_org_id uuid,
  p_target_user_id uuid,
  p_minutes integer default 15
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token text;
  v_minutes integer := greatest(1, least(coalesce(p_minutes, 15), 120));
begin
  if not public.platform_is_founder(auth.uid()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;

  v_token := encode(gen_random_bytes(24), 'hex');

  insert into public.platform_audit_events (
    actor_user_id, org_id, event_type, entity_type, entity_id, metadata
  )
  values (
    auth.uid(),
    p_org_id,
    'support.view_as_started',
    'support_session',
    v_token,
    jsonb_build_object(
      'target_user_id', p_target_user_id,
      'expires_at', now() + make_interval(mins => v_minutes)
    )
  );

  return v_token;
end;
$$;

insert into public.platform_permission_catalog_versions (status, created_by, published_by, publish_note, published_at)
select 'published', null, null, 'Initial baseline imported from permission_catalog', now()
where not exists (
  select 1 from public.platform_permission_catalog_versions v where v.status = 'published'
);

insert into public.platform_permission_catalog_entries (
  version_no, key, label, description, category, is_founder_only, is_archived
)
select
  v.version_no,
  pc.key,
  pc.label,
  pc.description,
  split_part(pc.key, '.', 1),
  pc.is_founder_only,
  false
from public.permission_catalog pc
join lateral (
  select version_no
  from public.platform_permission_catalog_versions
  where status = 'published'
  order by version_no desc
  limit 1
) v on true
on conflict (version_no, key) do nothing;

alter table public.platform_permission_catalog_versions enable row level security;
alter table public.platform_permission_catalog_entries enable row level security;
alter table public.platform_role_presets enable row level security;
alter table public.platform_audit_events enable row level security;

drop policy if exists platform_permission_catalog_versions_founder_select on public.platform_permission_catalog_versions;
create policy platform_permission_catalog_versions_founder_select
  on public.platform_permission_catalog_versions
  for select to authenticated
  using (public.platform_is_founder(auth.uid()));

drop policy if exists platform_permission_catalog_entries_founder_select on public.platform_permission_catalog_entries;
create policy platform_permission_catalog_entries_founder_select
  on public.platform_permission_catalog_entries
  for select to authenticated
  using (public.platform_is_founder(auth.uid()));

drop policy if exists platform_role_presets_founder_select on public.platform_role_presets;
create policy platform_role_presets_founder_select
  on public.platform_role_presets
  for select to authenticated
  using (public.platform_is_founder(auth.uid()));

drop policy if exists platform_audit_events_founder_select on public.platform_audit_events;
create policy platform_audit_events_founder_select
  on public.platform_audit_events
  for select to authenticated
  using (public.platform_is_founder(auth.uid()));

revoke all on function public.platform_is_founder(uuid) from public;
grant execute on function public.platform_is_founder(uuid) to authenticated, service_role;
revoke all on function public.platform_latest_published_catalog_version() from public;
grant execute on function public.platform_latest_published_catalog_version() to authenticated, service_role;
revoke all on function public.platform_latest_draft_catalog_version() from public;
grant execute on function public.platform_latest_draft_catalog_version() to authenticated, service_role;
revoke all on function public.platform_ensure_latest_draft_catalog() from public;
grant execute on function public.platform_ensure_latest_draft_catalog() to authenticated, service_role;
revoke all on function public.platform_founder_catalog_draft() from public;
grant execute on function public.platform_founder_catalog_draft() to authenticated, service_role;
revoke all on function public.platform_upsert_catalog_draft_entry(text, text, text, text, boolean, boolean) from public;
grant execute on function public.platform_upsert_catalog_draft_entry(text, text, text, text, boolean, boolean) to authenticated, service_role;
revoke all on function public.platform_publish_catalog(text) from public;
grant execute on function public.platform_publish_catalog(text) to authenticated, service_role;
revoke all on function public.platform_active_permission_catalog() from public;
grant execute on function public.platform_active_permission_catalog() to authenticated, service_role;
revoke all on function public.platform_list_role_presets(boolean) from public;
grant execute on function public.platform_list_role_presets(boolean) to authenticated, service_role;
revoke all on function public.platform_founder_upsert_role_preset(text, text, text, text, text[], boolean) from public;
grant execute on function public.platform_founder_upsert_role_preset(text, text, text, text, text[], boolean) to authenticated, service_role;
revoke all on function public.platform_list_audit_events(uuid, text, integer) from public;
grant execute on function public.platform_list_audit_events(uuid, text, integer) to authenticated, service_role;
revoke all on function public.platform_update_org_governance(uuid, text, text, boolean, boolean, boolean) from public;
grant execute on function public.platform_update_org_governance(uuid, text, text, boolean, boolean, boolean) to authenticated, service_role;
revoke all on function public.platform_create_support_session(uuid, uuid, integer) from public;
grant execute on function public.platform_create_support_session(uuid, uuid, integer) to authenticated, service_role;
